name: Test Build Tools

on:
  workflow_dispatch:
  schedule:
    # every sunday at 00:00
    - cron: "0 0 * * 0"

# remove all permission
permissions: {}

jobs:
  test-build-tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          # rspack
          - {name: "@rspack/core", version: latest}
          - {name: "@rspack/core", version: alpha}
          - {name: "@rspack/core", version: beta}
          - {name: "@rspack/core", version: 1.1.8}

          # webpack
          - {name: webpack, version: latest}
          - {name: webpack, version: 5.73.0}

          # esbuild
          - {name: esbuild, version: latest}
          - {name: esbuild, version: 0.19.12}

          # rollup
          - {name: rollup, version: latest}
          - {name: rollup, version: beta}
          - {name: rollup, version: 4.22.5}
          - {name: rollup, version: 4.17.0}

          # rolldown
          - {name: rolldown, version: latest}
          - {name: rolldown, version: canary}
          - {name: rolldown, version: nightly}
          - {name: rolldown, version: 0.15.1}

          # vite
          - {name: vite, version: latest}
          - {name: vite, version: 6.0.2}
      fail-fast: false

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*

      - name: install
        run: pnpm install --frozen-lockfile

      - name: install build tool
        run: pnpm add -Dw ${{ matrix.tool.name }}@${{ matrix.tool.version }}

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test

      - name: typecheck
        run: pnpm typecheck
